# Generated by Django 3.2.5 on 2021-11-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_posting_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posting',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='posting',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
