# Generated by Django 3.2.5 on 2021-11-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20211105_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
