# Generated by Django 3.2.5 on 2021-11-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20211111_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
