# Generated by Django 3.2.5 on 2021-11-18 06:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_posting_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
