# Generated by Django 3.2.5 on 2021-11-18 07:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_posting_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
